/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/background-jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * In-process background ParseAll / UpdateTasks jobs
         * @description Local ops status for active tracker sync jobs started via `/cron/{slug}/…`.
         *     Public (no apikey). Empty `jobs` array when nothing is running.
         */
        get: operations["healthBackgroundJobs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Build version info */
        get: operations["version"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lastupdatedb": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Last FileDB update time */
        get: operations["lastUpdateDb"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1.0/conf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Validate API key
         * @description Returns whether the provided apikey matches server configuration. Whitelisted without apikey.
         */
        get: operations["checkApiKey"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2.0/indexers/{status}/results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Jackett-compatible search */
        get: operations["jackettSearch"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1.0/torrents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Native torrent search */
        get: operations["torrentsSearch"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1.0/qualitys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Quality aggregation by title */
        get: operations["qualitys"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/torznab/api": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Torznab API (caps, search)
         * @description Native Torznab XML when torznab.enable is true.
         *     Supported search params match caps (`q`, `imdbid`, `tvdbid`, `season`, `ep`) plus JacRed card fields.
         */
        get: operations["torznabRoot"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        /**
         * Torznab HEAD probe
         * @description Returns empty Torznab XML body (same content-type as GET).
         */
        head: operations["torznabRootHead"];
        patch?: never;
        trace?: never;
    };
    "/api/v2.0/indexers/{indexer}/results/torznab/api": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Torznab API (indexer path)
         * @description Same handler as `/torznab/api` (Jackett-style indexer URL).
         */
        get: operations["torznabIndexer"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2.0/indexers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List configured indexers (Jackett/Prowlarr) */
        get: operations["indexersList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/indexer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Prowlarr indexer list
         * @description Prowlarr-compatible indexer list for discover clients (qui, autobrr) and Prowlarr apps.
         *     Returns a JSON array with `enable: true` and `protocol: torrent`.
         */
        get: operations["prowlarrIndexerList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/indexer/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Prowlarr indexer detail
         * @description Prowlarr-compatible indexer detail for qui tracker domain resolution (backend=prowlarr).
         *     JacRed exposes a single aggregate indexer with `id=1`.
         */
        get: operations["prowlarrIndexerDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/indexer/{indexer}/newznab": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Prowlarr Torznab proxy
         * @description Prowlarr-compatible Torznab endpoint (`t=caps`, `search`, `tvsearch`, `moviesearch`).
         *     Same handler as `/torznab/api` and Jackett alias paths.
         */
        get: operations["prowlarrNewznab"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Prowlarr Search Feed
         * @description Prowlarr-compatible interactive search (`/api/v1/search`).
         *     Returns a JSON array of ReleaseResource-shaped objects.
         *     Brace tokens in `query` (e.g. `{ImdbId:tt123}`, `{Season:1}`) are parsed like Prowlarr UI search.
         *     JacRed exposes a single aggregate torrent indexer (`id=1`); `indexerIds=-1` (usenet) returns `[]`.
         *     Each release also includes JacRed extensions (`ffprobe`, `languages`, `info`) when `tracks: true`, same as Jackett results.
         *     Lampa Prowlarr mode (`query` + `type` + `categories`) is promoted to Jackett-style card search
         *     (`title`/`title_original`/`year`, `is_serial` 1=movie / 2=serial) for richer TV/movie results.
         */
        get: operations["prowlarrSearch"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats/torrents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Tracker summary (stats.json)
         * @description All trackers from Data/temp/stats.json. Used by web UI `/stats`.
         *     When `openstats: false`, still returns **200** with body `[]` (soft disable; not a middleware 401).
         *     Missing/invalid API key (when configured) is a separate **401**.
         */
        get: operations["statsTorrents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats/tracks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Tracks export aggregate (tracks-stats.json cache)
         * @description Read-only cache from Data/temp/tracks-stats.json. Force refresh via `/dev/TracksStats?refresh=true`.
         *     When `openstats: false`, still returns **200** with `{ ok: false }` (soft disable; not a middleware 401).
         *     Missing/invalid API key (when configured) is a separate **401**.
         */
        get: operations["statsTracks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Last stats collection time
         * @description Returns updatedAt for stats.json and tracks-stats.json. Used by web UI `/stats`.
         *     When `openstats: false`, still returns **200** with `{ ok: false }` (soft disable; not a middleware 401).
         *     Missing/invalid API key (when configured) is a separate **401**.
         */
        get: operations["statsMeta"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sync/conf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sync protocol metadata */
        get: operations["syncConf"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sync/fdb": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sync FileDB key listing
         * @description Requires `opensync: true` in server config.
         */
        get: operations["syncFdb"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sync/fdb/torrents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sync FileDB torrent collections
         * @description Returns torrent batches changed after `time`. Supports spidr mode and incremental `start`. Requires `opensync: true`.
         */
        get: operations["syncFdbTorrents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sync/torrents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Legacy sync torrents stub
         * @deprecated
         * @description Deprecated stub. Always returns `{ error: "use GET /sync/fdb/torrents" }`.
         *     Prefer `/sync/fdb/torrents`.
         */
        get: operations["syncTorrentsStub"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1.0/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current configuration
         * @description Returns parsed config as JSON object and serialized content (secrets included).
         *     **LAN or valid X-Dev-Key** (same-host proxy alone is not sufficient).
         */
        get: operations["configGet"];
        put?: never;
        /**
         * Save configuration
         * @description Writes to init.yaml or init.conf. Hot-reload within ~10s. **LAN or valid X-Dev-Key.**
         */
        post: operations["configSave"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1.0/config/schema": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Form schema for settings UI */
        get: operations["configSchema"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1.0/config/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate configuration without saving */
        post: operations["configValidate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1.0/config/diff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Diff proposed config vs current
         * @description Used by settings UI before save confirmation.
         */
        post: operations["configDiff"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1.0/config/render": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Serialize form data to YAML/JSON
         * @description Form ↔ raw editor sync (settings UI).
         */
        post: operations["configRender"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1.0/config/parse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Parse YAML/JSON text to JSON object */
        post: operations["configParse"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1.0/config/format": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Pretty-print config after AppInit normalization
         * @description Validates, normalizes through AppInit model, returns formatted YAML/JSON.
         */
        post: operations["configFormat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/openapi.yaml": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** OpenAPI specification (YAML) */
        get: operations["openApiYaml"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/opensearch.xml": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * OpenSearch description document
         * @description Browser/search-plugin discovery for JacRed HTML search (`/?s={searchTerms}`).
         */
        get: operations["openSearchXml"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search PWA */
        get: operations["webSearch"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Statistics PWA */
        get: operations["webStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Settings PWA */
        get: operations["webSettings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Internal tracker id (FileDB / cron / synctrackers)
         * @example korsars
         * @enum {string}
         */
        TrackerSlug: "anibelka" | "anidub" | "anifilm" | "aniliberty" | "animelayer" | "anistar" | "baibako" | "bitru" | "kinozal" | "knaben" | "korsars" | "leproduction" | "lostfilm" | "mazepa" | "megapeer" | "nnmclub" | "rutor" | "rutracker" | "selezen" | "toloka" | "torrentby" | "ultradox" | "viruseproject";
        HealthResponse: {
            /** @example OK */
            status?: string;
        };
        BackgroundJobsResponse: {
            jobs: components["schemas"]["BackgroundJob"][];
        };
        BackgroundJob: {
            /** @description Internal job key */
            key?: string;
            /** @description Tracker slug */
            tracker?: string;
            /** @description Human-readable job label (e.g. ParseAll, UpdateTasks) */
            jobLabel?: string;
            /** Format: date-time */
            startedAtUtc?: string;
            /** @description Seconds since startedAtUtc */
            ageSec?: number;
            progressCurrent?: number | null;
            progressTotal?: number | null;
            progressDetail?: string | null;
        };
        VersionResponse: {
            version?: string;
            gitSha?: string;
            gitBranch?: string;
            buildDate?: string;
        };
        /** @description Prowlarr /api/v1/indexer list item */
        ProwlarrIndexer: {
            /** @example 1 */
            id?: number;
            name?: string;
            description?: string;
            /** @example Torznab */
            implementation?: string;
            /** @example Torznab */
            implementationName?: string;
            enable?: boolean;
            /**
             * @example torrent
             * @enum {string}
             */
            protocol?: "unknown" | "usenet" | "torrent";
        };
        /** @description Prowlarr /api/v1/indexer/{id} detail response */
        ProwlarrIndexerDetail: {
            /** @example 1 */
            id?: number;
            name?: string;
            description?: string;
            implementation?: string;
            implementationName?: string;
            enable?: boolean;
            fields?: Record<string, never>[];
        };
        /** @description Prowlarr /api/v1/search ReleaseResource item */
        ProwlarrRelease: {
            guid?: string;
            age?: number;
            ageHours?: number;
            ageMinutes?: number;
            /** Format: int64 */
            size?: number;
            /** @example 1 */
            indexerId?: number;
            indexer?: string;
            title?: string;
            sortTitle?: string;
            /** Format: date-time */
            publishDate?: string;
            downloadUrl?: string | null;
            magnetUrl?: string | null;
            infoUrl?: string | null;
            commentUrl?: string | null;
            categories?: {
                id?: number;
                name?: string;
                subCategories?: Record<string, never>[];
            }[];
            /**
             * @example torrent
             * @enum {string}
             */
            protocol?: "unknown" | "usenet" | "torrent";
            infoHash?: string | null;
            seeders?: number;
            leechers?: number;
            /** @description ffprobe streams when tracks is enabled (JacRed extension) */
            ffprobe?: {
                [key: string]: unknown;
            }[] | null;
            /** @description Detected language codes (JacRed extension) */
            languages?: string[] | null;
            /** @description JacRed torrent metadata (voices, seasons, types, …) */
            info?: {
                [key: string]: unknown;
            } | null;
        };
        ErrorResponse: {
            /** @example false */
            ok?: boolean;
            error?: string;
        };
        /** @description Provide either `data` (JSON object) or `content` (YAML/JSON string) */
        ConfigSaveRequest: {
            /** @description Parsed configuration object (preferred for form UI) */
            data?: {
                [key: string]: unknown;
            };
            /** @description Raw init.yaml or init.conf text */
            content?: string;
            /**
             * @description Format hint for content or output file
             * @enum {string}
             */
            format?: "yaml" | "json";
        };
        ConfigGetResponse: {
            ok?: boolean;
            /** @example init.yaml */
            path?: string;
            /**
             * @description Path to example config file shipped with the app
             * @example Data/example.yaml
             */
            examplePath?: string;
            /** @enum {string} */
            format?: "yaml" | "json";
            displayFormat?: string;
            exists?: boolean;
            /** Format: date-time */
            lastModifiedUtc?: string;
            /** @description Parsed config (includes secrets; LAN or devkey) */
            data?: {
                [key: string]: unknown;
            };
            /** @description Serialized config text */
            content?: string;
            schema?: components["schemas"]["ConfigFormSchema"];
            sensitiveFields?: string[];
            note?: string;
        };
        ConfigSaveResponse: {
            ok?: boolean;
            path?: string;
            format?: string;
            /** Format: date-time */
            lastModifiedUtc?: string;
            message?: string;
        };
        ConfigValidationResponse: {
            ok?: boolean;
            error?: string;
            /** @description Blocking validation errors */
            errors?: string[];
            /** @description Non-blocking warnings */
            warnings?: string[];
        };
        ConfigDiffEntry: {
            /** @example listenport */
            path?: string;
            oldValue?: string | null;
            newValue?: string | null;
            sensitive?: boolean;
            /** @enum {string} */
            change?: "added" | "removed" | "changed";
        };
        ConfigDiffResponse: {
            ok?: boolean;
            diffs?: components["schemas"]["ConfigDiffEntry"][];
            changeCount?: number;
            validation?: components["schemas"]["ConfigValidationResponse"];
        };
        ConfigRenderResponse: {
            ok?: boolean;
            content?: string;
            /** @enum {string} */
            format?: "yaml" | "json";
        };
        ConfigFormatResponse: {
            ok?: boolean;
            data?: {
                [key: string]: unknown;
            };
            /** @description Pretty-printed YAML or JSON */
            content?: string;
            /** @enum {string} */
            format?: "yaml" | "json";
        };
        ConfigFormSchema: {
            groups?: {
                id?: string;
                title?: string;
                description?: string;
                fields?: components["schemas"]["ConfigFieldSchema"][];
                trackers?: Record<string, never>[];
            }[];
        };
        ConfigFieldSchema: {
            key?: string;
            /** @enum {string} */
            type?: "string" | "int" | "bool" | "password" | "stringList" | "select" | "json";
            label?: string;
            description?: string;
            sensitive?: boolean;
            min?: number;
            max?: number;
            enumValues?: string[];
        };
        JackettRootObject: {
            Results?: components["schemas"]["JackettResult"][];
            /**
             * @description Always true for JacRed responses (read-only marker)
             * @example true
             */
            jacred?: boolean;
        };
        JackettResult: {
            Tracker?: string;
            Title?: string;
            /** @description Size in bytes (may be fractional from parsers) */
            Size?: number;
            Seeders?: number;
            Peers?: number;
            MagnetUri?: string;
            /** Format: uri */
            Details?: string;
            PublishDate?: string;
            /** @description Torznab category ids */
            Category?: number[];
            CategoryDesc?: string;
            /** @description ffprobe streams when tracks is enabled */
            ffprobe?: {
                [key: string]: unknown;
            }[] | null;
            languages?: string[];
            info?: {
                quality?: number;
                videotype?: string;
                voices?: string[];
                seasons?: number[];
                types?: string[];
                sizeName?: string;
                name?: string;
                originalname?: string;
                relased?: number;
            };
        };
        TorrentQuality: {
            qualitys?: number[];
            types?: string[];
            languages?: string[];
            /** Format: date-time */
            createTime?: string;
            /** Format: date-time */
            updateTime?: string;
        };
        TorrentListItem: {
            tracker?: components["schemas"]["TrackerSlug"];
            title?: string;
            /** Format: int64 */
            size?: number;
            sizeName?: string;
            url?: string | null;
            createTime?: string;
            updateTime?: string;
            sid?: number;
            pir?: number;
            magnet?: string;
            name?: string;
            originalname?: string;
            relased?: number;
            types?: string[];
            videotype?: string;
            quality?: number;
            voices?: string[];
            seasons?: number[];
        };
        TrackerTracks: {
            wait?: number;
            confirm?: number;
            skip?: number;
        };
        TrackerStat: {
            trackerName: components["schemas"]["TrackerSlug"];
            lastnewtor?: string | null;
            newtor?: number | null;
            update?: number | null;
            check?: number | null;
            alltorrents?: number | null;
            tracks?: components["schemas"]["TrackerTracks"] | null;
        };
        StatsMeta: {
            ok?: boolean;
            /** Format: date-time */
            updatedAt?: string | null;
            updatedAtLocal?: string | null;
            /** Format: date-time */
            tracksStatsUpdatedAt?: string | null;
        };
    };
    responses: {
        /** @description Missing or invalid API key */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        /** @description API key (alternative — X-Api-Key header or Bearer) */
        ApiKeyQuery: string;
        /** @description Torznab function (`caps`, `indexers`, or search type) */
        TorznabT: "caps" | "indexers" | "search" | "tvsearch" | "movie" | "tv" | "moviesearch";
        /** @description Free-text search query */
        TorznabQ: string;
        /** @description Comma-separated Torznab category ids */
        TorznabCat: string;
        /** @description IMDb id (`tt…` or bare digits); aliases `imdb_id`, `imdbId` also accepted */
        TorznabImdbId: string;
        /** @description TheTVDB id (tv-search) */
        TorznabTvdbId: string;
        /** @description Alias for `tvdbid` */
        TorznabRid: string;
        /** @description Season number (tv-search filter) */
        TorznabSeason: number;
        /** @description Episode number (tv-search filter) */
        TorznabEp: number;
        /** @description Alias for `ep` */
        TorznabEpisode: number;
        /** @description Localized title (JacRed / Lampa card search) */
        TorznabTitle: string;
        /** @description Original title (JacRed / Lampa card search) */
        TorznabTitleOriginal: string;
        /** @description Max results after filters */
        TorznabLimit: number;
        /** @description Result offset for pagination */
        TorznabOffset: number;
        /**
         * @description Used with `t=indexers`. Omit, empty, or `true` returns the JacRed indexer list XML;
         *     `false` returns an empty `<indexers>` document.
         * @example true
         */
        TorznabConfigured: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is running */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    healthBackgroundJobs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active background jobs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BackgroundJobsResponse"];
                };
            };
        };
    };
    version: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Version metadata */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionResponse"];
                };
            };
        };
    };
    lastUpdateDb: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Last update timestamp */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example 04.07.2026 15:30 */
                        lastupdatedb?: string;
                    };
                };
            };
        };
    };
    checkApiKey: {
        parameters: {
            query?: {
                /** @description API key (alternative — X-Api-Key header or Bearer) */
                apikey?: components["parameters"]["ApiKeyQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Key validation result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description true if key is valid or server has no apikey configured */
                        apikey?: boolean;
                    };
                };
            };
        };
    };
    jackettSearch: {
        parameters: {
            query?: {
                /** @description API key (alternative — X-Api-Key header or Bearer) */
                apikey?: components["parameters"]["ApiKeyQuery"];
                query?: string;
                title?: string;
                title_original?: string;
                year?: number;
                is_serial?: number;
                /** @description Jackett/Lampa categories (e.g. 2000 movies, 5000 TV, 5070 anime) */
                "Category[]"?: string[];
                /** @description Jackett-style filter by internal tracker id */
                "Tracker[]"?: components["schemas"]["TrackerSlug"][];
                /** @description Single-tracker alias for Tracker[] */
                tracker?: components["schemas"]["TrackerSlug"];
            };
            header?: never;
            path: {
                status: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Search results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JackettRootObject"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    torrentsSearch: {
        parameters: {
            query?: {
                /** @description API key (alternative — X-Api-Key header or Bearer) */
                apikey?: components["parameters"]["ApiKeyQuery"];
                /** @description Empty or omitted yields an empty result array */
                search?: string;
                altname?: string;
                exact?: boolean;
                type?: string;
                sort?: "sid" | "pir" | "size" | "create" | "update";
                tracker?: components["schemas"]["TrackerSlug"];
                voice?: string;
                videotype?: string;
                relased?: number;
                quality?: number;
                season?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ordered torrent result array (maximum 2000 items) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TorrentListItem"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    qualitys: {
        parameters: {
            query?: {
                /** @description API key (alternative — X-Api-Key header or Bearer) */
                apikey?: components["parameters"]["ApiKeyQuery"];
                name?: string;
                originalname?: string;
                type?: string;
                page?: number;
                take?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /**
             * @description Nested map: title key → release year → TorrentQuality.
             *     Empty name and originalname yields `{}`.
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: {
                            [key: string]: components["schemas"]["TorrentQuality"];
                        };
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    torznabRoot: {
        parameters: {
            query?: {
                /** @description API key (alternative — X-Api-Key header or Bearer) */
                apikey?: components["parameters"]["ApiKeyQuery"];
                /** @description Torznab function (`caps`, `indexers`, or search type) */
                t?: components["parameters"]["TorznabT"];
                /** @description Free-text search query */
                q?: components["parameters"]["TorznabQ"];
                /** @description Comma-separated Torznab category ids */
                cat?: components["parameters"]["TorznabCat"];
                /** @description IMDb id (`tt…` or bare digits); aliases `imdb_id`, `imdbId` also accepted */
                imdbid?: components["parameters"]["TorznabImdbId"];
                /** @description TheTVDB id (tv-search) */
                tvdbid?: components["parameters"]["TorznabTvdbId"];
                /** @description Alias for `tvdbid` */
                rid?: components["parameters"]["TorznabRid"];
                /** @description Season number (tv-search filter) */
                season?: components["parameters"]["TorznabSeason"];
                /** @description Episode number (tv-search filter) */
                ep?: components["parameters"]["TorznabEp"];
                /** @description Alias for `ep` */
                episode?: components["parameters"]["TorznabEpisode"];
                /** @description Localized title (JacRed / Lampa card search) */
                title?: components["parameters"]["TorznabTitle"];
                /** @description Original title (JacRed / Lampa card search) */
                title_original?: components["parameters"]["TorznabTitleOriginal"];
                /** @description Max results after filters */
                limit?: components["parameters"]["TorznabLimit"];
                /** @description Result offset for pagination */
                offset?: components["parameters"]["TorznabOffset"];
                /**
                 * @description Used with `t=indexers`. Omit, empty, or `true` returns the JacRed indexer list XML;
                 *     `false` returns an empty `<indexers>` document.
                 * @example true
                 */
                configured?: components["parameters"]["TorznabConfigured"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Torznab XML */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/xml": string;
                };
            };
            /** @description Torznab disabled */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    torznabRootHead: {
        parameters: {
            query?: {
                /** @description API key (alternative — X-Api-Key header or Bearer) */
                apikey?: components["parameters"]["ApiKeyQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Empty XML OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/xml": string;
                };
            };
            /** @description Torznab disabled */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    torznabIndexer: {
        parameters: {
            query?: {
                /** @description API key (alternative — X-Api-Key header or Bearer) */
                apikey?: components["parameters"]["ApiKeyQuery"];
                /** @description Torznab function (`caps`, `indexers`, or search type) */
                t?: components["parameters"]["TorznabT"];
                /** @description Free-text search query */
                q?: components["parameters"]["TorznabQ"];
                /** @description Comma-separated Torznab category ids */
                cat?: components["parameters"]["TorznabCat"];
                /** @description IMDb id (`tt…` or bare digits); aliases `imdb_id`, `imdbId` also accepted */
                imdbid?: components["parameters"]["TorznabImdbId"];
                /** @description TheTVDB id (tv-search) */
                tvdbid?: components["parameters"]["TorznabTvdbId"];
                /** @description Alias for `tvdbid` */
                rid?: components["parameters"]["TorznabRid"];
                /** @description Season number (tv-search filter) */
                season?: components["parameters"]["TorznabSeason"];
                /** @description Episode number (tv-search filter) */
                ep?: components["parameters"]["TorznabEp"];
                /** @description Alias for `ep` */
                episode?: components["parameters"]["TorznabEpisode"];
                /** @description Localized title (JacRed / Lampa card search) */
                title?: components["parameters"]["TorznabTitle"];
                /** @description Original title (JacRed / Lampa card search) */
                title_original?: components["parameters"]["TorznabTitleOriginal"];
                /** @description Max results after filters */
                limit?: components["parameters"]["TorznabLimit"];
                /** @description Result offset for pagination */
                offset?: components["parameters"]["TorznabOffset"];
                /**
                 * @description Used with `t=indexers`. Omit, empty, or `true` returns the JacRed indexer list XML;
                 *     `false` returns an empty `<indexers>` document.
                 * @example true
                 */
                configured?: components["parameters"]["TorznabConfigured"];
            };
            header?: never;
            path: {
                indexer: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Torznab XML */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/xml": string;
                };
            };
            /** @description Torznab disabled */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    indexersList: {
        parameters: {
            query?: {
                /** @description API key (alternative — X-Api-Key header or Bearer) */
                apikey?: components["parameters"]["ApiKeyQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Indexer list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>[];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    prowlarrIndexerList: {
        parameters: {
            query?: {
                /** @description API key (alternative — X-Api-Key header or Bearer) */
                apikey?: components["parameters"]["ApiKeyQuery"];
            };
            header?: {
                "X-Api-Key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Enabled torrent indexers */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProwlarrIndexer"][];
                };
            };
            /** @description Torznab disabled */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    prowlarrIndexerDetail: {
        parameters: {
            query?: {
                /** @description API key (alternative — X-Api-Key header or Bearer) */
                apikey?: components["parameters"]["ApiKeyQuery"];
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Indexer detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProwlarrIndexerDetail"];
                };
            };
            /** @description Torznab disabled or unknown indexer id */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    prowlarrNewznab: {
        parameters: {
            query?: {
                /** @description API key (alternative — X-Api-Key header or Bearer) */
                apikey?: components["parameters"]["ApiKeyQuery"];
                /** @description Torznab function (`caps`, `indexers`, or search type) */
                t?: components["parameters"]["TorznabT"];
                /** @description Free-text search query */
                q?: components["parameters"]["TorznabQ"];
                /** @description Comma-separated Torznab category ids */
                cat?: components["parameters"]["TorznabCat"];
                /** @description IMDb id (`tt…` or bare digits); aliases `imdb_id`, `imdbId` also accepted */
                imdbid?: components["parameters"]["TorznabImdbId"];
                /** @description TheTVDB id (tv-search) */
                tvdbid?: components["parameters"]["TorznabTvdbId"];
                /** @description Alias for `tvdbid` */
                rid?: components["parameters"]["TorznabRid"];
                /** @description Season number (tv-search filter) */
                season?: components["parameters"]["TorznabSeason"];
                /** @description Episode number (tv-search filter) */
                ep?: components["parameters"]["TorznabEp"];
                /** @description Alias for `ep` */
                episode?: components["parameters"]["TorznabEpisode"];
                /** @description Localized title (JacRed / Lampa card search) */
                title?: components["parameters"]["TorznabTitle"];
                /** @description Original title (JacRed / Lampa card search) */
                title_original?: components["parameters"]["TorznabTitleOriginal"];
                /** @description Max results after filters */
                limit?: components["parameters"]["TorznabLimit"];
                /** @description Result offset for pagination */
                offset?: components["parameters"]["TorznabOffset"];
                /**
                 * @description Used with `t=indexers`. Omit, empty, or `true` returns the JacRed indexer list XML;
                 *     `false` returns an empty `<indexers>` document.
                 * @example true
                 */
                configured?: components["parameters"]["TorznabConfigured"];
            };
            header?: never;
            path: {
                indexer: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Torznab XML */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/xml": string;
                };
            };
            /** @description Torznab disabled */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    prowlarrSearch: {
        parameters: {
            query?: {
                /** @description API key (alternative — X-Api-Key header or Bearer) */
                apikey?: components["parameters"]["ApiKeyQuery"];
                /** @description URL-encoded search string (supports Prowlarr brace tokens) */
                query?: string;
                /** @description Alias for `query` when `query` is empty */
                q?: string;
                type?: "search" | "tvsearch" | "movie" | "music" | "book";
                /**
                 * @description Comma-separated or repeated; `1` or `-2` (torrents) select JacRed; omit = all; `-1` = usenet (empty)
                 * @example 1
                 */
                indexerIds?: string;
                /** @description Repeat for each category (e.g. categories=2000&categories=5000) */
                categories?: number;
                /** @description Localized title (JacRed / Lampa card search) */
                title?: components["parameters"]["TorznabTitle"];
                /** @description Original title (JacRed / Lampa card search) */
                title_original?: components["parameters"]["TorznabTitleOriginal"];
                /** @description Release year override (Lampa / card search) */
                year?: number;
                /** @description Max results after filters */
                limit?: components["parameters"]["TorznabLimit"];
                /** @description Result offset for pagination */
                offset?: components["parameters"]["TorznabOffset"];
            };
            header?: {
                "X-Api-Key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Search results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProwlarrRelease"][];
                };
            };
            /** @description Torznab disabled */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    statsTorrents: {
        parameters: {
            query?: {
                /** @description API key (alternative — X-Api-Key header or Bearer) */
                apikey?: components["parameters"]["ApiKeyQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tracker summary array (or `[]` when openstats is false) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrackerStat"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    statsTracks: {
        parameters: {
            query?: {
                /** @description API key (alternative — X-Api-Key header or Bearer) */
                apikey?: components["parameters"]["ApiKeyQuery"];
                includeTorrentDb?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tracks export aggregate (or `{ ok: false }` when openstats is false) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ok?: boolean;
                        /** Format: date-time */
                        updatedAt?: string;
                        fromCache?: boolean;
                        stats?: Record<string, never>;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    statsMeta: {
        parameters: {
            query?: {
                /** @description API key (alternative — X-Api-Key header or Bearer) */
                apikey?: components["parameters"]["ApiKeyQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Collection timestamps (or `{ ok: false }` when openstats is false) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsMeta"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    syncConf: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sync capabilities */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        fbd?: boolean;
                        spidr?: boolean;
                        version?: number;
                    };
                };
            };
        };
    };
    syncFdb: {
        parameters: {
            query?: {
                key?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description FDB sync payload */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    syncFdbTorrents: {
        parameters: {
            query: {
                time: number;
                start?: number;
                spidr?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Collections with nextread pagination flag */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    syncTorrentsStub: {
        parameters: {
            query?: {
                time?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect-style error payload */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example use GET /sync/fdb/torrents */
                        error?: string;
                    };
                };
            };
        };
    };
    configGet: {
        parameters: {
            query?: {
                /** @description Serialization format for content field */
                format?: "yaml" | "json";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Configuration payload */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigGetResponse"];
                };
            };
            /** @description Invalid or missing devkey */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden (LAN or devkey required) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    configSave: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfigSaveRequest"];
            };
        };
        responses: {
            /** @description Saved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigSaveResponse"];
                };
            };
            /** @description Invalid devkey */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden (LAN or devkey required) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    configSchema: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Field groups and validation metadata */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ok?: boolean;
                        schema?: components["schemas"]["ConfigFormSchema"];
                    };
                };
            };
        };
    };
    configValidate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfigSaveRequest"];
            };
        };
        responses: {
            /** @description Validation result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigValidationResponse"];
                };
            };
        };
    };
    configDiff: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfigSaveRequest"];
            };
        };
        responses: {
            /** @description Diff entries and validation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigDiffResponse"];
                };
            };
        };
    };
    configRender: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    data: {
                        [key: string]: unknown;
                    };
                    /**
                     * @default yaml
                     * @enum {string}
                     */
                    format?: "yaml" | "json";
                };
            };
        };
        responses: {
            /** @description Formatted text */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigRenderResponse"];
                };
            };
        };
    };
    configParse: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    content: string;
                    /** @enum {string} */
                    format?: "yaml" | "json";
                };
            };
        };
        responses: {
            /** @description Parsed configuration */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ok?: boolean;
                        data?: {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
    };
    configFormat: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfigSaveRequest"];
            };
        };
        responses: {
            /** @description Normalized data and formatted text */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigFormatResponse"];
                };
            };
        };
    };
    openApiYaml: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description This document */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/yaml": string;
                };
            };
        };
    };
    openSearchXml: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OpenSearchDescription XML */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/opensearchdescription+xml": string;
                };
            };
        };
    };
    webSearch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description HTML */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
        };
    };
    webStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description HTML */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
        };
    };
    webSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description HTML */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
        };
    };
}
